const constants = {
  DATABASE_PROVIDER_SERVICE: "DATABASE_PROVIDER_SERVICE",
  DATABASE_PROVIDER_ARANGO: "DATABASE_PROVIDER_ARANGO",
  DATABASE_PROVIDER_MOCK: "DATABASE_PROVIDER_MOCK",
};

export default constants;
