const constants = {
  IDENTITY_PROVIDER_SERVICE: "IDENTITY_PROVIDER_SERVICE",
  IDENTITY_PROVIDER_FIREBASE: "IDENTITY_PROVIDER_FIREBASE",
  IDENTITY_PROVIDER_MOCK: "IDENTITY_PROVIDER_MOCK",
};

export default constants;
